[project]
name = "minka-link"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-framework>=1.0.0b251120",
    "azure-identity>=1.15.0",
    "pypdf>=6.0.0",
    "azure-cosmos>=4.14.0",
]
